//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcLifeCycle.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class StickyNote
    {
        public int Id { get; set; }
        public string Text { get; set; }
        public string Colour { get; set; }
        public string Width { get; set; }
        public string Height { get; set; }
        public string Left { get; set; }
        public string Top { get; set; }
    }
}
